import { describe, it, expect } from 'vitest';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { planMotorFactory, planSize } from './support/factoryPlan';

/**
 * Serializes the verified plan for the act-3 browser spec.
 *
 * The e2e must drive the same layout the unit tests proved, not a parallel
 * copy that drifts: it imports the generated module. A `.ts` artifact rather
 * than `.json` because Playwright's Node runtime rejects bare JSON imports
 * without an import attribute the build does not otherwise need.
 */
describe('e2e plan artifact', () => {
  // The planner's search takes ~10-20s cold (up to 200 routing orders).
  it('exports the verified plan for the browser playthrough', { timeout: 120_000 }, () => {
    const plan = planMotorFactory();
    const size = planSize(plan);
    // Guard against exporting a degenerate plan the e2e would flake on.
    expect(size.machines).toBeGreaterThanOrEqual(20);
    expect(size.total).toBeLessThan(400);

    const artifact = {
      machines: plan.machines.map((m) => ({ type: m.type, x: m.x, y: m.y, rotation: m.rotation })),
      belts: plan.belts.map((b) => ({ type: 'belt' as const, ...b })),
      // Crossings have no facing of their own (cosmetic in the sim), but the
      // browser spec's rotation tracker needs a number to hold onto.
      crossings: plan.crossings.map((c) => ({ type: 'crossing' as const, ...c, rotation: 0 as const })),
    };

    const out = resolve(__dirname, 'support/e2ePlan.ts');
    const body = `// GENERATED by tests/exportE2EPlan.test.ts — do not edit by hand.
// Regenerate: npx vitest run tests/exportE2EPlan.test.ts
// This is the exact layout tests/factoryPlan.test.ts verified headlessly;
// e2e/act3.spec.ts drives it through the real UI.

export interface PlanThing {
  type: string;
  x: number;
  y: number;
  rotation: number;
}

export interface PlannedFactory {
  machines: PlanThing[];
  belts: PlanThing[];
  crossings: PlanThing[];
}

export const E2E_PLAN: PlannedFactory = ${JSON.stringify(artifact, null, 2)};
`;
    writeFileSync(out, body);

    // Round-trip: the artifact the e2e imports is exactly what was verified.
    const reloaded = JSON.parse(JSON.stringify(artifact)) as typeof artifact;
    expect(reloaded.machines).toHaveLength(plan.machines.length);
    expect(reloaded.belts).toHaveLength(plan.belts.length);
    expect(reloaded.crossings).toHaveLength(plan.crossings.length);
  });
});
