// GENERATED by tests/exportE2EPlan.test.ts — do not edit by hand.
// Regenerate: npx vitest run tests/exportE2EPlan.test.ts
// This is the exact layout tests/factoryPlan.test.ts verified headlessly;
// e2e/act3.spec.ts drives it through the real UI.

export interface PlanThing {
  type: string;
  x: number;
  y: number;
  rotation: number;
}

export interface PlannedFactory {
  machines: PlanThing[];
  belts: PlanThing[];
  crossings: PlanThing[];
}

export const E2E_PLAN: PlannedFactory = {
  "machines": [
    {
      "type": "silo",
      "x": 36,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "smelter",
      "x": 37,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "assembler",
      "x": 40,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "assembler",
      "x": 44,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "assembler",
      "x": 50,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "depot",
      "x": 52,
      "y": 46,
      "rotation": 0
    },
    {
      "type": "silo",
      "x": 40,
      "y": 50,
      "rotation": 90
    },
    {
      "type": "smelter",
      "x": 41,
      "y": 50,
      "rotation": 90
    },
    {
      "type": "silo",
      "x": 41,
      "y": 49,
      "rotation": 180
    },
    {
      "type": "assembler",
      "x": 44,
      "y": 50,
      "rotation": 0
    },
    {
      "type": "silo",
      "x": 45,
      "y": 50,
      "rotation": 90
    },
    {
      "type": "smelter",
      "x": 46,
      "y": 50,
      "rotation": 180
    },
    {
      "type": "silo",
      "x": 46,
      "y": 58,
      "rotation": 90
    },
    {
      "type": "smelter",
      "x": 47,
      "y": 58,
      "rotation": 90
    },
    {
      "type": "silo",
      "x": 47,
      "y": 57,
      "rotation": 180
    },
    {
      "type": "assembler",
      "x": 50,
      "y": 58,
      "rotation": 0
    },
    {
      "type": "silo",
      "x": 42,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "smelter",
      "x": 43,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "silo",
      "x": 43,
      "y": 53,
      "rotation": 180
    },
    {
      "type": "assembler",
      "x": 46,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "assembler",
      "x": 50,
      "y": 54,
      "rotation": 0
    },
    {
      "type": "extractor",
      "x": 32,
      "y": 15,
      "rotation": 180
    },
    {
      "type": "extractor",
      "x": 42,
      "y": 34,
      "rotation": 180
    },
    {
      "type": "extractor",
      "x": 16,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "extractor",
      "x": 40,
      "y": 35,
      "rotation": 180
    },
    {
      "type": "extractor",
      "x": 29,
      "y": 17,
      "rotation": 180
    },
    {
      "type": "extractor",
      "x": 44,
      "y": 36,
      "rotation": 180
    },
    {
      "type": "extractor",
      "x": 27,
      "y": 30,
      "rotation": 180
    },
    {
      "type": "extractor",
      "x": 35,
      "y": 18,
      "rotation": 180
    }
  ],
  "belts": [
    {
      "type": "belt",
      "x": 42,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 43,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 32,
      "y": 16,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 17,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 18,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 19,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 20,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 21,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 22,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 23,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 24,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 25,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 26,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 27,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 28,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 29,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 30,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 31,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 32,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 33,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 34,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 35,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 36,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 37,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 32,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 33,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 34,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 35,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 39,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 40,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 36,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 36,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 36,
      "y": 42,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 37,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 37,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 37,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 37,
      "y": 45,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 38,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 38,
      "y": 47,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 40,
      "y": 47,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 42,
      "y": 47,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 43,
      "y": 47,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 43,
      "y": 48,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 43,
      "y": 49,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 43,
      "y": 52,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 35,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 36,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 37,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 41,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 43,
      "y": 41,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 44,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 44,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 44,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 44,
      "y": 44,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 45,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 45,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 45,
      "y": 47,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 45,
      "y": 48,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 45,
      "y": 49,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 46,
      "y": 49,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 47,
      "y": 49,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 47,
      "y": 50,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 47,
      "y": 51,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 47,
      "y": 52,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 47,
      "y": 53,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 47,
      "y": 55,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 47,
      "y": 56,
      "rotation": 270
    },
    {
      "type": "belt",
      "x": 46,
      "y": 56,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 46,
      "y": 57,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 17,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 18,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 19,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 20,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 21,
      "y": 38,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 22,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 22,
      "y": 39,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 23,
      "y": 39,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 23,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 23,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 23,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 23,
      "y": 43,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 24,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 24,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 24,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 24,
      "y": 46,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 24,
      "y": 47,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 25,
      "y": 47,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 26,
      "y": 47,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 26,
      "y": 48,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 27,
      "y": 48,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 49,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 50,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 28,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 29,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 30,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 31,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 32,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 33,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 34,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 35,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 36,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 37,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 38,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 40,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 41,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 42,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 44,
      "y": 51,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 45,
      "y": 51,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 46,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 47,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 49,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 40,
      "y": 36,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 37,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 39,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 40,
      "y": 44,
      "rotation": 270
    },
    {
      "type": "belt",
      "x": 39,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 39,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 39,
      "y": 48,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 39,
      "y": 50,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 39,
      "y": 52,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 39,
      "y": 53,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 39,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 40,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 41,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 29,
      "y": 18,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 19,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 20,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 21,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 22,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 23,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 24,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 25,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 26,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 27,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 28,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 29,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 30,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 31,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 32,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 33,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 34,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 35,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 36,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 37,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 29,
      "y": 42,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 30,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 30,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 30,
      "y": 44,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 31,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 31,
      "y": 45,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 32,
      "y": 45,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 33,
      "y": 45,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 34,
      "y": 45,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 35,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 46,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 47,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 36,
      "y": 47,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 37,
      "y": 47,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 37,
      "y": 48,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 38,
      "y": 48,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 38,
      "y": 49,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 51,
      "y": 46,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 50,
      "y": 53,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 52,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 51,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 50,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 49,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 48,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 47,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 44,
      "y": 37,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 44,
      "y": 38,
      "rotation": 270
    },
    {
      "type": "belt",
      "x": 43,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 43,
      "y": 39,
      "rotation": 270
    },
    {
      "type": "belt",
      "x": 41,
      "y": 39,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 41,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 41,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 41,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 41,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 41,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 41,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 41,
      "y": 48,
      "rotation": 270
    },
    {
      "type": "belt",
      "x": 40,
      "y": 48,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 44,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 45,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 46,
      "y": 51,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 46,
      "y": 52,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 46,
      "y": 53,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 44,
      "y": 49,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 44,
      "y": 48,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 44,
      "y": 47,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 57,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 56,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 50,
      "y": 55,
      "rotation": 0
    },
    {
      "type": "belt",
      "x": 49,
      "y": 54,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 42,
      "y": 50,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 27,
      "y": 31,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 32,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 33,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 34,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 35,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 36,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 37,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 27,
      "y": 39,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 28,
      "y": 39,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 30,
      "y": 39,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 31,
      "y": 39,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 31,
      "y": 40,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 32,
      "y": 40,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 33,
      "y": 40,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 34,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 34,
      "y": 41,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 35,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 43,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 36,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 36,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 36,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 19,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 20,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 35,
      "y": 21,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 36,
      "y": 21,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 36,
      "y": 22,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 36,
      "y": 23,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 36,
      "y": 24,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 37,
      "y": 24,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 38,
      "y": 24,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 38,
      "y": 25,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 39,
      "y": 25,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 40,
      "y": 25,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 41,
      "y": 25,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 42,
      "y": 25,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 26,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 27,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 42,
      "y": 28,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 43,
      "y": 28,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 44,
      "y": 28,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 44,
      "y": 29,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 45,
      "y": 29,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 45,
      "y": 30,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 46,
      "y": 30,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 46,
      "y": 31,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 46,
      "y": 32,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 46,
      "y": 33,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 47,
      "y": 33,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 47,
      "y": 34,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 48,
      "y": 34,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 35,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 36,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 37,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 38,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 39,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 40,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 41,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 42,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 43,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 44,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 45,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 47,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 48,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 49,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 50,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 51,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 52,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 53,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 55,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 56,
      "rotation": 180
    },
    {
      "type": "belt",
      "x": 48,
      "y": 57,
      "rotation": 270
    },
    {
      "type": "belt",
      "x": 48,
      "y": 58,
      "rotation": 90
    },
    {
      "type": "belt",
      "x": 49,
      "y": 58,
      "rotation": 90
    }
  ],
  "crossings": [
    {
      "type": "crossing",
      "x": 43,
      "y": 51,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 45,
      "y": 46,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 39,
      "y": 47,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 39,
      "y": 51,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 39,
      "y": 49,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 38,
      "y": 46,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 39,
      "y": 46,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 42,
      "y": 39,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 41,
      "y": 46,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 41,
      "y": 47,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 40,
      "y": 49,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 47,
      "y": 54,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 43,
      "y": 50,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 29,
      "y": 39,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 48,
      "y": 46,
      "rotation": 0
    },
    {
      "type": "crossing",
      "x": 48,
      "y": 54,
      "rotation": 0
    }
  ]
};
